default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: bellroy_trial_development

test:
  <<: *default
  database: bellroy_trial_test

production:
  <<: *default
  database: bellroy_trial_production
  username: bellroy_trial
  password: <%= ENV['BELLROY_TRIAL_DATABASE_PASSWORD'] %>
